name: Generate Stats Images

on:
  push:
    branches: [ master ]
  schedule:
    # "At 00:00 on Monday."
    - cron: "0 0 * * 1" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Run using Python 3.8 for consistency and aiohttp
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        architecture: 'x64'
        cache: 'pip' # caching pip dependencies

    - name: Install requirements
      run: |
        python3 -m pip install -r requirements.txt

    - name: Generate images
      run: |
        python3 generate_images.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Commit to the repo
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        # "echo" returns true so the build succeeds, even if no changed files
        git commit -m 'Update' || echo
        git push
